import { getAllArchives } from '../lib/archives';

export async function GET() {
  const archives = getAllArchives();

  function escapeXml(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  const items = archives.map((a) => {
    const title = a.frontmatter.title || 'Untitled Digest';
    const link = `https://ntrevino.github.io/ai-digests/archives/${a.slug}`;
    const date = a.frontmatter.date ? new Date(a.frontmatter.date).toUTCString() : new Date().toUTCString();
    // Use excerpt as description
    const body = a.body.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
    const description = escapeXml(body.slice(0, 500) + (body.length > 500 ? '…' : ''));

    return `
    <item>
      <title>${escapeXml(title)}</title>
      <link>${escapeXml(link)}</link>
      <guid>${escapeXml(link)}</guid>
      <pubDate>${date}</pubDate>
      <description>${description}</description>
      <category>${escapeXml(a.frontmatter.type || 'general')}</category>
    </item>`;
  }).join('');

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>AI Digests</title>
    <link>https://ntrevino.github.io/ai-digests/</link>
    <description>Curated weekly digests generated by AI — frontend ecosystem and rabbit hole discoveries.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="https://ntrevino.github.io/ai-digests/rss.xml" rel="self" type="application/rss+xml"/>
    ${items}
  </channel>
</rss>`;

  return new Response(rss, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
